name: AWS Lambda Zip Deploy - Python
author: Qubitro
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  pip_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  custom_layers:
    - path:
        description: the path to the code for the layer
      arn:
        description: The ARN for the Lambda layer where custom code should be pushed
  lambda_functions:
    - name:
        description: The Lambda function's name. Check the AWS docs/readme for examples.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.pip_layer_arn }}
    - ${{ inputs.custom_layers }}
    - ${{ inputs.lambda_functions }}
    - ${{ inputs.lambda_region }}
branding:
  icon: 'cloud-lightning'
  color: 'white'
